name: Infralovers Container Build

on:
  workflow_dispatch:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]


permissions:
  packages: write
  contents: write
  id-token: write
  pull-requests: write
  

jobs:
  build:
    uses: infralovers/.github/.github/workflows/container.yml@main
    with:
      dockerfile: Dockerfile
      platforms: "linux/amd64, linux/arm64"
      release: true
